libs/libsysnds/Makefile.arm7
libs/libsysnds/Makefile.arm9
libs/libsysnds/include/aeabi.h
libs/libsysnds/include/ndsabi.h
libs/libsysnds/source/common/ndsabi/LICENSE.md
libs/libsysnds/source/common/ndsabi/fiq_memcpy.s
libs/libsysnds/source/common/ndsabi/macros.inc
libs/libsysnds/source/common/ndsabi/memcpy.s
libs/libsysnds/source/common/ndsabi/memmove.s
libs/libsysnds/source/common/ndsabi/memset.s
libs/libsysnds/source/common/ndsabi/rmemcpy.s

These are derived from the zlib-licensed [agbabi project](https://github.com/felixjones/agbabi) (with adjustments to work correctly on an NDS-targetting toolchain with ARM/Thumb interwork), and have been extensively tested by myself to be both more performant than the newlib/picolibc defaults (which are written in C and not ARMv4-optimized), and correctly functioning.
There are other routines in agbabi, and I hope to see more of them provided upon verifying licensing and functionality. (I've ran into undiagnosed issues with using agbabi memset(), in particular.) Future work may also include checking if these routines can receive ARMv5-specific optimizations.

libsysnds: introduce agbabi-derived fast memcpy/memmove routines

---

libs/libsysnds/source/arm9/fatfs/cache.c
libs/libsysnds/source/arm9/fatfs/diskio.c

* Speed up the cache eviction loop by bailing if a given cache entry is not used anymore. (This also might fix subtracting below 0, potentially causing an underflow. Should we be subtracting here, anyway? Directory entries could fall out of use quite quickly...)
* Use a round robin approach to eviction.
* Don't cache reads which are >1 sector and pointing to main RAM. These will only ever come from large (>1 sector) reads in FatFS, and as FatFS also caches one sector's worth of data, it is redundant to do so.
* Move cache invalidation to the DLDI handler itself - see matching libnds PR. It makes more sense to be there, IMO.
* Fix `disk_write` passing unaligned byte buffers to the DLDI device driver. This is not reliable across all DLDI drivers.

libsysnds: cache, diskio improvements

---

.gitmodules

Building into the SDK PATH directory is untested, but it does compile via the makefile.

Initial import of dldipatch

---

tools/mkfatimg/source/main.c

This line:
`RamDiskSize = atoi(argv[ai++]) * 2;`
assumed that argc > 3, which is not always true when it gets to this point. I fixed this by changing the line to
`RamDiskSize = (argc >= 4) ? atoi(argv[ai++]) * 2 : 0;`
which automatically sets `RamDiskSize` to `0` if argc < 4, which avoids a segmentation fault.

Fix segmentation fault

---

sys/crts/ds_arm9.ld

This has some advantages over the old approach:
- The developer can define the DLDI driver area size supported by their .nds file. A 32KB DLDI driver area size is required for some legacy homebrew launchers; conversely, a space-constrained program could set it to a lower value, like 8KB.
- The DLDI driver area is guaranteed to be placed close to the beginning of the .nds file, which may slightly speed up DLDI patch times, including on-console.

crts: Define explicit DLDI driver area.

---

sys/crts/Makefile
sys/crts/dldi_arm7.specs
sys/crts/dldi_arm9.specs
sys/crts/ds_arm7.specs
sys/crts/ds_arm7_iwram.specs
sys/crts/ds_arm7_vram.specs
sys/crts/ds_arm9.specs
sys/crts/dsi_arm9.specs
sys/default_arm7/Makefile
sys/default_makefiles/rom_arm9/Makefile
sys/default_makefiles/rom_arm9arm7/Makefile.arm7
sys/default_makefiles/rom_arm9arm7/Makefile.arm9
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm7
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm9
sys/default_makefiles/rom_arm9arm7teak/Makefile.teak
sys/default_makefiles/rom_arm9teak/Makefile.arm9
sys/default_makefiles/rom_arm9teak/Makefile.teak
templates/dldi/Makefile
templates/library_arm9_only/Makefile
templates/library_combined/Makefile.arm7
templates/library_combined/Makefile.arm9
templates/rom_arm9_only/Makefile
templates/rom_combined/Makefile.arm7
templates/rom_combined/Makefile.arm9

There's a few benefits resulting from this:
* All of the architecture-specific compiler configuration (CPU architecture, linker quirks, crt0 file, etc.) are moved to a single specs file. This allows simplifying Makefiles, as well as changing these things without breaking Makefiles in the wild.
* The GCC specs files include `picolibc.specs`, which is now provided by Wonderful. This, in turn, allows *me* to break the picolibc library/include layout at will without breaking Makefiles in the wild.
* I've added the `__BLOCKSDS__` define, to distinguish BlocksDS installations from other toolchains - we've added enough functionality now that there's an increasing need for such a define, IMO.
* The `picolibc.specs` adds support for picolibc's officially supported method of changing the …

sys, templates: migrate to using GCC specs files, simplify Makefiles

---

sys/default_arm7/source/main.c

Fixes https://github.com/blocksds/sdk/issues/117

sys: initialize camera FIFO in default ARM7 implementation

---

sys/crts/dldi_arm7.specs
sys/crts/dldi_arm9.specs
sys/crts/ds_arm7.specs
sys/crts/ds_arm7_iwram.specs
sys/crts/ds_arm7_vram.specs
sys/crts/ds_arm9.specs
sys/crts/dsi_arm9.specs
sys/default_arm7/Makefile
sys/default_makefiles/rom_arm9/Makefile
sys/default_makefiles/rom_arm9arm7/Makefile.arm7
sys/default_makefiles/rom_arm9arm7/Makefile.arm9
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm7
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm9
sys/default_makefiles/rom_arm9teak/Makefile.arm9
templates/dldi/Makefile
templates/library_arm9_only/Makefile
templates/library_combined/Makefile.arm7
templates/library_combined/Makefile.arm9
templates/rom_arm9_only/Makefile
templates/rom_combined/Makefile.arm7
templates/rom_combined/Makefile.arm9

Unfortunately, the C++ driver doesn't use all the fields that the C driver does. In particular:
* `cpp` is ignored - but we can patch around this in the specs file.
* `cc1_cpu` is ignored - unfortunately, we cannot patch around this in the specs file, so I needed to bring back `mcpu` into the Makefiles.

sys, templates: specs file fixes

---

sys/default_makefiles/rom_arm9/Makefile
sys/default_makefiles/rom_arm9arm7/Makefile.arm7
sys/default_makefiles/rom_arm9arm7/Makefile.arm9
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm7
sys/default_makefiles/rom_arm9arm7teak/Makefile.arm9
sys/default_makefiles/rom_arm9arm7teak/Makefile.teak
sys/default_makefiles/rom_arm9teak/Makefile.arm9
sys/default_makefiles/rom_arm9teak/Makefile.teak
templates/dldi/Makefile
templates/library_arm9_only/Makefile
templates/library_combined/Makefile.arm7
templates/library_combined/Makefile.arm9
templates/rom_arm9_only/Makefile
templates/rom_combined/Makefile.arm7
templates/rom_combined/Makefile.arm9

This allows flexibility in the event a user needs to build multiple binaries from the same source code. For example, if one needs builds with a specific DEFINE, and another without such a DEFINE, just a NAME change will make sure these do not conflict, while also making it relatively easy for a user to see which build directory is related to which Makefile.
Test: compile
You can find an example at https://github.com/lifehackerhansol/flashcard-bootstrap, where this logic is applied for the ARM9 binaries.

templates: use build/$(NAME) for build directory

---

tests/filesystem/stress_test/source/main.c

Regressed in 0.12.0; thankfully not an SDK bug.

tests: Fix filesystem stress test.

---

docs/content/technical/devkitarm_porting_guide.md

For select "advanced" projects, such as a port of a source code that was not designed with devkitARM in mind, it is common practice to have a "platform" Makefile in a subdirectory that calls directories that are out of the scope of said Makefile's PWD.
This behaviour is unsupported in BlocksDS at this time. It should be noted.

devkitarm_porting_guide: note relative paths outside PWD is not supported

---

docs/content/introduction/changelog.md
docs/content/technical/updating_guide.md

This assumes the three outstanding PRs of mine have been merged, so don't merge it before that.
It also fixes formatting in the BlocksDS 1.2.0 changelog by moving the individual, uncategorized `libnds` changes to a new section "Other".

docs: Update changelog

---

tools/dlditool/dlditool.c

Fixes the definition of `bool` in dlditool which is not compliant with C23.

C23 compatibility

---

tools/teaktool/source/main.c

C's `__DATE__` prevents reproducible builds[[1](https://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html)]; some LLVM frontends enforce build reproducibility (e.g. Zig) and so this does not compile. 
`__DATE__` is also present in ndstool

Remove usage of __DATE__

---

sys/default_makefiles/rom_arm9/Makefile
sys/default_makefiles/rom_arm9arm7/Makefile
sys/default_makefiles/rom_arm9arm7teak/Makefile
sys/default_makefiles/rom_arm9teak/Makefile

(don't overwrite sdroot or sdimage if already defined in default makefiles)

default_makefiles: Make SD root configurable

---

tools/Makefile

This causes some funny stuff if "V" is in the build env (very common in debian build systems)

Add missing V variable in Makefile

---

sys/crts/dldi.ld
sys/crts/ds_arm7.ld
sys/crts/ds_arm7_crt0.s
sys/crts/ds_arm7_iwram.ld
sys/crts/ds_arm7_vram.ld
sys/crts/ds_arm9.ld
sys/crts/ds_arm9_crt0.s

- Add a new user-configurable symbol, __dtcm_data_size. By default, it is set to 0, mimicking old behaviour (DTCM data placed at beginning of DTCM, stack placed at end of DTCM). However, if it is set to a non-zero value, DTCM data is placed at the end of DTCM, with stacks placed before it; this, in particular, allows the user stack to extend past DTCM and into main RAM.
- Add a new user-configurable symbol, __shared_wram_size.
- Add assertions for user-configurable size symbols being multiples of four.
- Add .noinit section support to link scripts.
- Add missing Free Software Foundation copyright notices to link scripts.
- Update link scripts with later changes done in GCC to the original link scripts that BlocksDS-provided scripts derive from.
- Minor crt0 cleanups; some redundant code …

sys/crts: linkscript/crt0 upgrades

---

docker/Dockerfile
docker/build-docker.sh

Hi Antonio,
This PR is to add support for linux/arm64 platforms on the Docker image. This will allow users with 64 bit ARM computers (such as modern Macs and Raspberry Pis) to use BlocksDS on Docker natively. Builds were 8x faster on an M1 Mac mini, compared to emulation (16.526s vs 2m20.807s real time).
One thing to note is that llvm-teak is not available on aarch64/ARM64, so only the x86_64/AMD64 build includes the `toolchain-llvm-teak-llvm` package.
The `build-docker.sh` script was also updated to do a [multi-platform build](https://docs.docker.com/build/building/multi-platform/). A single image is produced, that can be run for both architectures. This process should be transparent to you on Docker Desktop, emulation is handled automatically.
You can try the ARM64 builds on an AMD64 …

Add ARM64 support to Docker image

---

sys/crts/ds_arm7_crt0.s
sys/crts/ds_arm9_crt0.s

- Fixed thread-local storage initialization on ARM7.
- Moved thread-local storage initialization to happen before global constructor initialization on ARM9 (in conjunction with related changes in libnds).
https://github.com/blocksds/libnds/pull/140

crts: fix thread-local storage initialization

---

.github/workflows/pacman.yaml
pacman/PKGBUILD

Extracted from `wonderful-packages` and slightly tweaked to work outside of that build system. To be done on your end:
- Figure out a versioning scheme. If you're going to ingest Git builds into your own repository, you might want to either include the number of Git commits in the package's version number (so updates work), or even have separate Git and  stable packages like I used to. I removed this from the PR for simplicity, but [this](https://github.com/WonderfulToolchain/wonderful-packages/blob/main/packages/thirdparty-blocksds/PKGBUILD#L5-L15) is what you need to have multiple package names in a multi-package project, and [this](https://github.com/WonderfulToolchain/wonderful-packages/blob/main/packages/templates/git-pkgver.PKGBUILD) allows pulling in information from the Git …

pacman: add build scripts and Linux GitHub CI

---

Makefile
examples/cmake/portable_demo/CMakeLists.txt
examples/cmake/portable_demo/README.md
examples/cmake/portable_demo/src/cross_platform_logic.c
examples/cmake/portable_demo/src/cross_platform_logic.h
examples/cmake/portable_demo/src/nds/main_nds.c
examples/cmake/portable_demo/src/posix/main_posix.c
sys/cmake/BlocksDS-rule-overrides.cmake
sys/cmake/BlocksDS.cmake
sys/cmake/BlocksDSi.cmake
sys/cmake/Platform/NintendoDS.cmake
sys/cmake/README.md

Here are my CMake build scripts. Fully rewritten but aimed at compatibility with existing projects targeting devkitPro CMake. ARM9 only since the aim is to facilitate cross-platform projects, not NDS-specific development.
This PR should not be merged until it has a Makefile to add these new files to the installation process.

Add CMake build scripts and documentation

---

sys/cmake/Platform/NintendoDS.cmake

This should fix the issue regarding a circular dependency between picolibc and libnds9 recently discussed on Discord.

NintendoDS.cmake: patch circular dependency link issue

---

examples/compression/bios_bit_unpack/source/main.c

These are unsigned integers anyways, so it makes sense to perform unsigned arithmetic rather than signed. Fixes a crash triggered when using undefined behavior sanitizers on this example.
Depends on https://github.com/blocksds/libnds/pull/149

examples: fix undefined left-shifts in compression/bios_bit_unpack example

---

docs/content/introduction/changelog.md

Accidentally spotted this omission today.

docs: Document missing 1.7.0 ndstool changes.

---

sys/cmake/Platform/NintendoDS.cmake

The `portable_demo` CMake example doesn't build currently. I get a complaint from the linker:
```
/opt/wonderful/toolchain/gcc-arm-none-eabi/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /opt/wonderful/toolchain/gcc-arm-none-eabi/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/lib/thumb/arm946e-s/libc.a(libc_time_time.c.o): in function `time':
/wf/packages/toolchain-gcc-arm-none-eabi-picolibc-generic/src/picolibc-build/../wf-picolibc/newlib/libc/time/time.c:54:(.text.time+0x8): undefined reference to `gettimeofday'
collect2: error: ld returned 1 exit status
```
Removing the first `-lc` from `STANDARD_LIBRARIES` in the platform file fixes this. I understand this was put in to address a circular dependency issue (#241) so I've opted to instead just use …

CMake: Use linker group for standard libraries

---

sys/cmake/BlocksDS.cmake

Allow creating a title with just 2 lines (omitting either `SUBTITLE` or `AUTHOR`). The default subtitles appear only appear when both are omitted. This more closely resembles the behavior of the template Makefiles (actually a little more flexible). `SUBTITLE1` and `SUBTITLE2` still work as aliases to `SUBTITLE` and `AUTHOR`.

cmake: Improve banner title formation

---

examples/dynamic_libs/Makefile
examples/dynamic_libs/basic_demo/.gitignore
examples/dynamic_libs/basic_demo/Makefile
examples/dynamic_libs/basic_demo/build.sh
examples/dynamic_libs/basic_demo/lib_calculator/Makefile
examples/dynamic_libs/basic_demo/lib_calculator/dsl.ld
examples/dynamic_libs/basic_demo/lib_calculator/source/calculator.c
examples/dynamic_libs/basic_demo/source/main.c
examples/dynamic_libs/readme.md
examples/readme.md
tools/dsltool/.gitignore
tools/dsltool/COPYING
tools/dsltool/Makefile
tools/dsltool/source/dsl.h
tools/dsltool/source/elf.c
tools/dsltool/source/elf.h
tools/dsltool/source/main.c
tools/dsltool/source/main_binary.c
tools/dsltool/source/main_binary.h
tools/dsltool/source/sym_table.c
tools/dsltool/source/sym_table.h

This PR introduces `dlstool`, a tool that converts `.elf` files into dynamic libraries in `.dsl` to be loaded by libnds.
It also adds an example of how to use it.
More context and discussion here:
https://github.com/blocksds/sdk/issues/44

WIP: Add initial dynamic library support

---

sys/crts/dldi.ld
sys/crts/ds_arm7.ld
sys/crts/ds_arm7_iwram.ld
sys/crts/ds_arm7_vram.ld
sys/crts/ds_arm9.ld

An optimization was implemented that I missed while checking regressions, and the newly required symbols were not caught by the linker either. Oops.

sys/crts: fix global initializers on picolibc 1.8.10

---

tools/dsltool/source/main.c

There is currently an inconsistency in how elf symbol indices are handled by dsltool -- in `sym_table.c` they are treated as 32-bit integers while in `main.c` they are single bytes. In `main.c` this leads to integer overflow when larger (or really even moderately-sized) symtables are processed.
This fix just changes them to signed 32-bit integers to match the declaration of `new_index` in `main.c`.

dsltool: Allow loading ELF files with more than 256 symbols
